INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
AVALANCHE_PATH_1: "./datasets/Avalanche_1/"
AVALANCHE_PATH_2: "./datasets/Avalanche_2/"
AVALANCHE_PATH_3: "./datasets/Avalanche_3/"
AVALANCHE_PATH_4: "./datasets/Avalanche_3a/"
AVALANCHE_PATH_5: "./datasets/Avalanche_3b/"
AVALANCHE_PATH_6: "./datasets/Avalanche_4/" # avalanche 4 contains train and vali photos
AVALANCHE_PATH_7: "./datasets/Avalanche_train/" # avalanche_train contains cropped train photos
AVALANCHE_PATH_8: "./datasets/Avalanche_vali/" # avalanche_train contains cropped vali photos
AVALANCHE_PATH_9: "./datasets/Avalanche_DG/" # avalanche Dg contains pics from Börterhorn/ unknown cam-domain gap

# Train datasets
SBD_PATH: "./datasets/SBD"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "./datasets/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"
AVALANCHE_TRAIN: "./datasets/Avalanche_train/"
AVALANCHE_VALI: "./datasets/Avalanche_vali/"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
